### ISSUE TITLE
forbidden message does not distinguish between org not having a data plan, and unauthenticated user

### ISSUE THREAD

**Issue by wkalt** [foxglove/foxglove-cli#29]
For example, this will be printed even if the org is not registered for data:
Import failed: Forbidden. Have you signed in with `foxglove login`?

**Comment by defunctzombie** [comment]
Is there a place where we return a 403 but could be a 401?

**Comment by defunctzombie** [comment]
Assigned to @wkalt to double check if this is still a thing.

**Comment by defunctzombie** [comment]
I am closing this. There's no such thing as an org without a data plan since we give folks free data.
