### ISSUE TITLE
built artifacts must be marked executable after download

### ISSUE THREAD

**Issue by wkalt** [foxglove/foxglove-cli#37]
This seems similar to the permissions limitations documented here, though I haven't investigated if the cause is the same:
https://github.com/actions/upload-artifact#limitations

Tarring the file isn't an obviously better solution to me than allowing the user to mark perms. If we can, we should figure out a way to make the download itself executable.

**Comment by amacneil** [comment]
Are downloaded files ever executable in linux/unix? I don't recall ever doing a `wget`/`curl` without needing to run `chmod +x` on it.

e.g. https://github.com/amacneil/dbmate#installation

**Comment by wkalt** [comment]
hmm yeah, I guess you're right. I must usually use package managers.
