### ISSUE TITLE
auth w/o browser?

### ISSUE THREAD

**Issue by itsderek23** [foxglove/foxglove-cli#38]
Our ros bag files are uploaded to a remote server. From there, we'd like to have a script upload these files to Foxglove. 

Do you have a suggested approach for this? We don't have a browser on this server and would like the flow to be automated.

**Comment by itsderek23** [comment]
This the error I see:

```
./foxglove auth login
Enter this code in your browser:  [CODE REMOVED]
Login failed: failed to open browser: exec: "xdg-open": executable file not found in $PATH
```

**Comment by defunctzombie** [comment]
👋 yea - for headless script I'd actually recommend using api keys.

On your organization page there is an API keys section: 
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/84792/153948903-8360e29e-0d83-45b5-ba9a-094248124e29.png">

Once you make a key you can use that directly with scripts for the API methods.

We don't have client language libraries that use the api keys yet but any basic http client library would be able to handle it. Happy to help more with this if you want to ping me in our slack.

**Comment by amacneil** [comment]
Created ticket for API key support in CLI: https://github.com/foxglove/foxglove-cli/issues/39
