### ISSUE TITLE
export as ros2 db3 file

### ISSUE THREAD

**Issue by wkalt** [foxglove/foxglove-cli#53]
ROS2 db3 files can't be exported from the server, but reading an mcap data stream into a sqlite file would not be too difficult within the CLI tool. This would be nice for ROS2 users who would like to recover their original db3.

Alternatively/additionally, we could put this in the mcap CLI tool, which could make sense since that's where the db3->mcap conversion already exists.

**Comment by jhurliman** [comment]
I would like `.mcap` -> `.bag` in the mcap CLI tool as well, let me know if it should be a separate ticket.
