### ISSUE TITLE
Rename repo to `foxglove/cli`

### ISSUE THREAD

**Issue by amacneil** [foxglove/foxglove-cli#60]
Let's simplify things - we only have one CLI.

**Comment by wkalt** [comment]
@amacneil my only concern with this is it's going to cause the repo to clone as "cli", which could conflict with all kinds of stuff and would also not be a useful name in a ~/repos directory or whatever.

What about renaming it to `foxglove/foxglove`?

**Comment by amacneil** [comment]
🤷 seems pretty common https://github.com/search?q=cli

people can clone it to whatever folder they want. realistically that's only foxglove employees anyway.
