### ISSUE TITLE
Newest release missing linux-arm64 binary. 

### ISSUE THREAD

**Issue by msmcconnell** [foxglove/foxglove-cli#98]
**Description**
The newest release is missing the linux-arm64 binary. 
- Version: 1.0.4
- Platform: Nvidia Orin AGX (Arm64)

**Steps To Reproduce**

curl -L https://github.com/foxglove/foxglove-cli/releases/latest/download/foxglove-linux-arm64

Outputs "Not Found"

**Expected Behavior**
Outputs actual file. This worked prior to 1.0.4 release

**Comment by wkalt** [comment]
@msmcconnell thanks for the report. This should be fixed in v1.0.5. We had a bug in our release job.
